name: PR review Copy for test
# This workflow is triggered when a PR review is submitted. It checks if the review is approved and runs a script to add labels to the PR based on the review.

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  add-owner-approved-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run add-labels-to-reviewed-pr.sh
        run: ./.github/workflows/scripts/add-labels-to-reviewed-pr.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR: ${{ github.event.number }}
          