name: Lint PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions: read-all

jobs:
  add-owner-approved-label:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run add-labels-to-reviewed-pr.sh
        run: ./.github/workflows/scripts/add-labels-to-reviewed-pr.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR: ${{ github.event.number }}
